#!/usr/bin/env node
/**
 * Phase 2: export the game catalog (app/src/main/assets/songs.json) from the
 * ingest database. Only songs with real ListenBrainz listen counts make the
 * cut, and `rank` is set to the listen count itself — so the app's five
 * percentile tiers are driven by real listening data instead of Deezer rank.
 *
 * Usage:  node scripts/export-catalog.ts [options]
 *   --min-listens <n>   minimum listen_count to include (default 1000)
 *   --min-year <year>   earliest release year (default 1990)
 *   --db <path>         ingest DB (default scripts/data/ingest.db)
 *   --out <path>        output (default app/src/main/assets/songs.json)
 */

import { writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { openDb } from "./ingest/db.ts";

// Must match TieredCatalog.MIN_POOL_SIZE in the app.
const MIN_POOL_SIZE = 25;

interface CatalogSong {
  readonly id: number;
  readonly title: string;
  readonly artist: string;
  readonly rank: number;
}

const { values } = parseArgs({
  options: {
    "min-listens": { type: "string", default: "1000" },
    "min-year": { type: "string", default: "1990" },
    db: { type: "string", default: "scripts/data/ingest.db" },
    out: { type: "string", default: "app/src/main/assets/songs.json" },
  },
});

const minListens = Number(values["min-listens"]);
const minYear = Number(values["min-year"]);
if (!Number.isInteger(minListens) || minListens < 1) {
  throw new Error(`--min-listens must be a positive integer, got "${values["min-listens"]}"`);
}
if (!Number.isInteger(minYear) || minYear < 1900 || minYear > 2100) {
  throw new Error(`--min-year must be a year, got "${values["min-year"]}"`);
}

const db = openDb(values.db);
const rows = db
  .prepare(
    `SELECT t.id AS id, t.title AS title, t.artist AS artist,
            r.listen_count AS listen_count
     FROM raw_tracks t
     JOIN track_tiers r ON r.track_id = t.id
     WHERE t.release_date >= ?
       AND r.listen_count IS NOT NULL
       AND r.listen_count >= ?
       AND t.title <> '' AND t.artist <> ''`,
  )
  .all(`${minYear}-01-01`, minListens);
db.close();

// The same song often appears as single + album versions under different
// Deezer ids; keep only the most-listened copy of each (title, artist) pair.
const byKey = new Map<string, CatalogSong>();
for (const row of rows) {
  const song: CatalogSong = {
    id: Number(row.id),
    title: String(row.title),
    artist: String(row.artist),
    rank: Number(row.listen_count),
  };
  const key = `${song.title.toLowerCase()} ${song.artist.toLowerCase()}`;
  const existing = byKey.get(key);
  if (!existing || song.rank > existing.rank) byKey.set(key, song);
}

const songs = [...byKey.values()].sort((a, b) => b.rank - a.rank);
if (songs.length < MIN_POOL_SIZE) {
  throw new Error(
    `Only ${songs.length} songs passed the filters (app needs >= ${MIN_POOL_SIZE}); ` +
      `lower --min-listens or re-run the ingest first.`,
  );
}

const file = {
  _note:
    "Generated by scripts/export-catalog.ts from scripts/data/ingest.db. " +
    `rank = ListenBrainz listen_count (min ${minListens}); tiers derive from it. ` +
    `All tracks released ${minYear}+.`,
  version: 1,
  generatedAtUtc: new Date().toISOString(),
  songs,
};
writeFileSync(values.out, `${JSON.stringify(file, null, 1)}\n`);
console.log(
  `Wrote ${songs.length} songs (deduped from ${rows.length} rows, ` +
    `min ${minListens} listens, ${minYear}+) to ${values.out}`,
);
console.log(
  `Top song: ${songs[0].title} — ${songs[0].artist} (${songs[0].rank.toLocaleString()} listens)`,
);
